# Generated by Django 5.0.6 on 2024-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
