# Generated by Django 5.0.6 on 2024-05-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
