# Generated by Django 5.0.6 on 2024-05-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_doctor_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_roles',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor'), ('ordinary_user', 'ordinary_user'), ('diagnos', 'diagnos')], default='ordinary_user', max_length=100),
        ),
    ]
