# Generated by Django 5.0.6 on 2024-05-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='type',
        ),
    ]
