# Generated by Django 5.0.6 on 2024-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diagnos_file',
            field=models.FileField(blank=True, null=True, upload_to='diagnostics-files/%Y/%m/%d/'),
        ),
    ]
